Issue 45 feat 로그인UI 퍼블리싱
SaveMeMungz/SaveMeMungz-Web pull request #37
Opened 2024-10-23 12:54 UTC by CosmicSandBox

## 📌 관련 이슈

- closed: #31 

## ✨ PR 세부 내용

로그인 UI,
회원가입 UI
퍼블리싱 완료 했습니다!

## ⌛ 소요 시간

8시간

2024-10-25 12:06 UTC, InKyungWoo commented on src/app/(auth)/login/page.jsx
> +    background: #e0e0e0; /* 팔레트에 없는 컬러여서 컬러코드로 입력했습니다 */
제가 피그마에서 한 페이지만 수정해뒀네요ㅜ `BACKGROUND_COLORS.divider` 로 #ddd 적용해주시면 됩니다!

2024-10-25 12:06 UTC, InKyungWoo commented on src/app/(auth)/sign-up/components/SignUpInput.jsx
> +    color: #ff6464; /* 팔레트에 없는 컬러여서 컬러코드로 입력했습니다 */
`TEXT_COLORS.red` 로 적용해주시면 됩니다!

2024-10-25 12:06 UTC, InKyungWoo commented on src/assets/images/login-question.png
images 폴더 말고 icons 폴더에 넣어뒀습니다! 중복 에셋은 삭제해주시면 좋을것 같아요

2024-10-25 15:19 UTC, InKyungWoo requested changes

2024-10-25 15:19 UTC, InKyungWoo commented on src/app/(auth)/login/page.jsx
> +    background-color: ${BACKGROUND_COLORS.default};
저희 배경화면 흰색으로 하기로 했는데 로그인, 회원가입 페이지만 민트색으로 하신 이유가 있을까요?

2024-10-25 15:19 UTC, InKyungWoo commented on src/app/(auth)/login/page.jsx
> +const StyledCheckbox = styled(Checkbox)`
antd 컴포넌트 사용하셨군요 크기가 너무 작아서 조금 키우면 좋을 것 같습니다!

2024-10-25 15:30 UTC, InKyungWoo requested changes

2024-10-25 15:30 UTC, InKyungWoo commented on src/app/(auth)/login/page.jsx
> +                    <Image src={symbolImg} alt="Symbol" layout="fill" objectFit="contain" />
저도 이거 vscode warning 떠서 알았는데, 이렇게 layout과 objectFit 속성을 직접 사용하던 방식이 바뀌어서 legacy prop이라고 합니다. 대신 `fill style={{ objectFit: 'contain'  }}` 로 변경해주시면 됩니다!

2024-10-28 12:00 UTC, CosmicSandBox commented on src/app/(auth)/login/page.jsx
> +    background: #e0e0e0; /* 팔레트에 없는 컬러여서 컬러코드로 입력했습니다 */
감사합니다!! 바로 수정했습니다
덕분에 스타일링할 때 너무 편리합니다

2024-10-28 12:02 UTC, CosmicSandBox commented on src/app/(auth)/sign-up/components/SignUpInput.jsx
> +    color: #ff6464; /* 팔레트에 없는 컬러여서 컬러코드로 입력했습니다 */
수정했습니다 감사합니다!

2024-10-28 12:04 UTC, CosmicSandBox commented on src/assets/images/login-question.png
아!! 해당 아이콘까지 다 넣어주셨었군요!!
다른 부분 에셋들도 다 넣어주셔서 너무 편하게 코드짰습니다 ㅜㅜ
초기설정 너무 잘해주셔서 코드 짜는데 배려 받는 기분 드는건 처음이었어요 감사합니다

2024-10-28 12:08 UTC, CosmicSandBox commented on src/app/(auth)/login/page.jsx
> +    background-color: ${BACKGROUND_COLORS.default};
엇 이 부분에 대해서 제가 노션을 통해서 한 번 더 확실하게 확인했어야 하는데 죄송합니다 ㅜㅜ
사실 조금 기억이 애매해서 고민중이었는데
카톡상으로 보내주셨던 이미지 배경이 민트색이어서 확인없이 바로 민트색으로 진행했던 것 같습니다
바로 수정하겠습니다!!

2024-10-28 12:56 UTC, CosmicSandBox commented on src/app/(auth)/login/page.jsx
> +const StyledCheckbox = styled(Checkbox)`
감사합니다!! 수정했습니다

2024-10-28 13:49 UTC, CosmicSandBox commented on src/app/(auth)/login/page.jsx
> +                    <Image src={symbolImg} alt="Symbol" layout="fill" objectFit="contain" />
감사합니다!! 처음 알게된 사실이네요
Next.js 13 이후로는 두번째 방식이 더욱 권장되는군요!
해당 방식에 맞게 해당하는 부분이 있는 모든 부분을 수정했습니다 :)

2024-10-28 13:51 UTC, CosmicSandBox commented
말씀해주신 부분들 수정 하였고
회의때 보였던 문제점 : SignUp 페이지에서 Show가 두개 묶여서 동작하는 것 -> 개별적으로 동작하도록 수정하였고
login 페이지에 padding bottom을 실수로 주어서 해당 값을 삭제하였습니다!
좋은 코드 리뷰 감사합니다! 덕분에 수정하면서 또 많이 배웠습니다!!

2024-10-28 18:40 UTC, InKyungWoo commented
10/28 페어프로그래밍 진행 내용: 
- 뷰포트 스크롤 문제 해결
- next/Image 컴포넌트로 수정, 
- 코드 리팩토링
- Antd 체크박스 컴포넌트 css(hover) 오버라이딩
- 네이버 아이콘 추가

2024-10-28 18:40 UTC, InKyungWoo approved these changes

2024-10-28 19:09 UTC, merged